spring:
  application:
    name: eventpulse-core-api
  main:
    allow-bean-definition-overriding: true

  # Configuração de conexão com o Banco de Dados
  datasource:
  # trocar futuramente
    url: jdbc:postgresql://localhost:5432/eventpulse_db 
    username: admin
    password: admin_password
    driver-class-name: org.postgresql.Driver

  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      # 'validate' porque usaremos o Flyway para criar as tabelas
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuração do Flyway (Migration)
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080